# Generated by Django 2.0.4 on 2018-04-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialauth',
            name='text_notifications',
            field=models.BooleanField(default=False),
        ),
    ]
