# Generated by Django 2.0.4 on 2018-04-10 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='socialauth',
            old_name='authId',
            new_name='auth_id',
        ),
        migrations.RenameField(
            model_name='socialauth',
            old_name='emailNotifications',
            new_name='email_notifications',
        ),
    ]
