# Generated by Django 2.0.4 on 2018-04-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialauth',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
