# Generated by Django 2.0.4 on 2018-04-17 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20180417_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailnotifications',
            name='is_online',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='emailnotifications',
            name='social_auth',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_auth', to='myapp.SocialAuth'),
        ),
    ]
