# Generated by Django 2.0.4 on 2018-04-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20180417_0609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialauth',
            name='last_following_user',
        ),
        migrations.AddField(
            model_name='socialauth',
            name='followers',
            field=models.TextField(null=True),
        ),
    ]
